# Generated by Django 4.2.28 on 2026-02-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name')),
                ('extension', models.TextField(db_column='Extension', null=True)),
                ('path', models.TextField(db_column='Path', null=True)),
                ('rate', models.IntegerField(db_column='Rate', null=True)),
                ('min_freq', models.FloatField(db_column='MinFreq', null=True)),
                ('max_freq', models.FloatField(db_column='MaxFreq', null=True)),
                ('bit_depth', models.IntegerField(db_column='BitDepth', null=True)),
                ('channels', models.IntegerField(db_column='Channels', null=True)),
                ('duration', models.FloatField(db_column='Duration', null=True)),
                ('rms_loudness', models.FloatField(db_column='RMSLoudness', null=True)),
                ('zero_crossing_rate', models.FloatField(db_column='ZeroCrossingRate', null=True)),
                ('spectral_centroid', models.FloatField(db_column='SpectralCentroid', null=True)),
                ('eq_20_250', models.FloatField(db_column='EQ_20_250_Hz', null=True)),
                ('eq_250_2000', models.FloatField(db_column='EQ_250_2000_Hz', null=True)),
                ('eq_2000_6000', models.FloatField(db_column='EQ_2000_6000_Hz', null=True)),
                ('eq_6000_20000', models.FloatField(db_column='EQ_6000_20000_Hz', null=True)),
                ('mfcc_1', models.FloatField(db_column='MFCC_1', null=True)),
                ('mfcc_2', models.FloatField(db_column='MFCC_2', null=True)),
                ('mfcc_3', models.FloatField(db_column='MFCC_3', null=True)),
                ('mfcc_4', models.FloatField(db_column='MFCC_4', null=True)),
                ('mfcc_5', models.FloatField(db_column='MFCC_5', null=True)),
                ('mfcc_6', models.FloatField(db_column='MFCC_6', null=True)),
                ('mfcc_7', models.FloatField(db_column='MFCC_7', null=True)),
                ('mfcc_8', models.FloatField(db_column='MFCC_8', null=True)),
                ('mfcc_9', models.FloatField(db_column='MFCC_9', null=True)),
                ('mfcc_10', models.FloatField(db_column='MFCC_10', null=True)),
                ('mfcc_11', models.FloatField(db_column='MFCC_11', null=True)),
                ('mfcc_12', models.FloatField(db_column='MFCC_12', null=True)),
                ('mfcc_13', models.FloatField(db_column='MFCC_13', null=True)),
                ('summary', models.TextField(db_column='Summary')),
                ('conflict', models.IntegerField(db_column='Conflict')),
                ('silence', models.FloatField(db_column='Silence')),
            ],
            options={
                'db_table': 'File',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name', unique=True)),
            ],
            options={
                'db_table': 'Topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.TextField(db_column='Speaker')),
                ('sequence', models.IntegerField(db_column='Sequence')),
                ('start_time', models.FloatField(db_column='StartTime')),
                ('end_time', models.FloatField(db_column='EndTime')),
                ('content', models.TextField(db_column='Content')),
                ('sentiment', models.TextField(db_column='Sentiment')),
                ('profane', models.IntegerField(db_column='Profane')),
            ],
            options={
                'db_table': 'Utterance',
                'ordering': ['sequence'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=2048)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.file')),
            ],
            options={
                'db_table': 'Job',
                'ordering': ['-created_at'],
            },
        ),
    ]
